import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  roadmapSidebar: [
    'intro',
    'roadmap',
    {
      type: 'category',
      label: 'DevOps Foundations',
      collapsed: false,
      items: [
        'foundations/index',
        'foundations/overview',
        'foundations/teaching',
        'foundations/incidents',
        'linux-networking/index',
        'linux-networking/overview',
        'linux-networking/teaching',
        'linux-networking/incidents',
        'git/index',
        'git/overview',
        'git/teaching',
        'git/incidents',
        'programming/index',
        'programming/overview',
        'programming/teaching',
        'programming/incidents',
      ],
    },
    {
      type: 'category',
      label: 'Cloud & Containers',
      collapsed: false,
      items: [
        'cloud/index',
        'cloud/overview',
        'cloud/teaching',
        'cloud/incidents',
        'docker/index',
        'docker/overview',
        'docker/teaching',
        'docker/incidents',
        'cicd/index',
        'cicd/overview',
        'cicd/teaching',
        'cicd/incidents',
        'kubernetes/index',
        'kubernetes/overview',
        'kubernetes/teaching',
        'kubernetes/incidents',
      ],
    },
    {
      type: 'category',
      label: 'Automation & GitOps',
      collapsed: false,
      items: [
        'terraform-ansible/index',
        'terraform-ansible/overview',
        'terraform-ansible/teaching',
        'terraform-ansible/incidents',
        'gitops/index',
        'gitops/overview',
        'gitops/teaching',
        'gitops/incidents',
      ],
    },
    {
      type: 'category',
      label: 'Security & Observability',
      collapsed: false,
      items: [
        'devsecops/index',
        'devsecops/overview',
        'devsecops/teaching',
        'devsecops/incidents',
        'observability/index',
        'observability/overview',
        'observability/teaching',
        'observability/incidents',
      ],
    },
    {
      type: 'category',
      label: 'Agentic AI',
      collapsed: false,
      items: [
        'ai-foundations/index',
        'ai-foundations/overview',
        'ai-foundations/teaching',
        'ai-foundations/incidents',
        'ai-agent-building/index',
        'ai-agent-building/overview',
        'ai-agent-building/teaching',
        'ai-agent-building/incidents',
        'ai-rag-memory/index',
        'ai-rag-memory/overview',
        'ai-rag-memory/teaching',
        'ai-rag-memory/incidents',
        'ai-production/index',
        'ai-production/overview',
        'ai-production/teaching',
        'ai-production/incidents',
        'cloud-native-agents/index',
        'cloud-native-agents/overview',
        'cloud-native-agents/teaching',
        'cloud-native-agents/incidents',
      ],
    },
    {
      type: 'category',
      label: 'Career & Mastery',
      collapsed: false,
      items: [
        'career/index',
        'career/overview',
        'career/teaching',
        'career/incidents',
        'ultra-pro/index',
        'ultra-pro/overview',
        'ultra-pro/teaching',
        'ultra-pro/incidents',
      ],
    },
    'about',
  ],
};

export default sidebars;
